from django.urls import path
from Bigflow.FA import views
urlpatterns = [
    # FA Pages
    path('fa_summary', views.fa_summary, name="fa_summary"),
    path('fa_assetadd/', views.fa_assetadd, name="fa_assetadd"),
    path('fa_assetchecker/', views.fa_assetchecker, name="fa_assetchecker"),
    path('fa_capdate_change/', views.fa_capdate_change, name="fa_capdate_change"),
    path('fa_capdate_changeplus/', views.fa_capdate_changeplus, name="fa_capdate_changeplus"),
    path('cp_datechecker/', views.fa_capdate_checker, name="fa_capdate_checker"),
    path('fa_asset_parentchild/', views.fa_asset_parentchild, name="fa_asset_parentchild"),
    path('fa_asset_parentchildcheck/', views.fa_asset_parentchildcheck, name="fa_asset_parentchildcheck"),
    path('fa_writeoff/', views.fa_writeoff, name="fa_writeoff"),
    path('fa_writeoffplus/', views.fa_writeoffplus, name="fa_writeoffplus"),
    path('fa_writeoff_check/', views.fa_writeoff_check, name="fa_writeoff_check"),
    path('fa_impairment/', views.fa_impairment, name="fa_impairment"),
    path('fa_impairmentplus/', views.fa_impairmentplus, name="fa_impairmentplus"),
    path('fa_impairment_check/', views.fa_impairment_check, name="fa_impairment_check"),
    path('fa_asset_merge/', views.fa_asset_merge, name="fa_asset_merge"),
    path('fa_asset_merge_plus/', views.fa_asset_merge_plus, name="fa_asset_merge_plus"),
    path('fa_asset_merge_checker/', views.fa_asset_merge_checker, name="fa_asset_merge_checker"),
    path('fa_asset_split/', views.fa_asset_split, name="fa_asset_split"),
    path('fa_asset_split_plus/', views.fa_asset_split_plus, name="fa_asset_split_plus"),
    path('fa_asset_split_checker/', views.fa_asset_split_checker, name="fa_asset_split_checker"),
    path('fa_asset_catgry/', views.fa_asset_catgry, name="fa_asset_catgry"),
    path('fa_asset_catgry_plus/', views.fa_asset_catgry_plus, name="fa_asset_catgry_plus"),
    path('fa_asset_catgrychecker/', views.fa_asset_catgrychecker, name="fa_asset_catgrychecker"),
    path('fa_asset_sale/', views.fa_asset_sale, name="fa_asset_sale"),
    path('fa_asset_saleplus/', views.fa_asset_saleplus, name="fa_asset_saleplus"),
    path('fa_asset_sale_checker/', views.fa_asset_sale_checker, name="fa_asset_sale_checker"),
    path('fa_value_reduction/', views.fa_value_reduction, name="fa_value_reduction"),
    path('fa_value_reduction_plus/', views.fa_value_reduction_plus, name="fa_value_reduction_plus"),
    path('fa_reduction_checker/', views.fa_reduction_checker, name="fa_reduction_checker"),
    path('fa_transfer_maker/', views.fa_transfer_maker, name="fa_transfer_maker"),
    path('fa_transferplus/', views.fa_transferplus, name="fa_transferplus"),
    path('fa_transfer_checker/', views.fa_transfer_checker, name="fa_transfer_checker"),
    path('fa_depreciation_calc/', views.fa_depreciation_calc, name="fa_depreciation_calc"),

    path('fa_financial_year/', views.fa_financial_year, name="fa_financial_year"),
    path('fa_financial_year_plus/', views.fa_financial_year_plus, name="fa_financial_year_plus"),
    path('fa_financial_year_checker/', views.fa_financial_year_checker, name="fa_financial_year_checker"),

    path('fa_physic_verify/', views.fa_physic_verify, name="fa_physic_verify"),
    path('fa_physic_verify_plus/', views.fa_physic_verify_plus, name="fa_physic_verify_plus"),
    path('fa_physic_verify_check/', views.fa_physic_verify_check, name="fa_physic_verify_check"),

    #cat Master
    path('fa_asset_catgry_master_plus/', views.fa_asset_catgry_master_plus, name="fa_asset_catgry_master_plus"),
    path('fa_asset_catgry_summary/', views.fa_asset_catgry_summary, name="fa_asset_catgry_summary"),

    # FA Fuctions
    path('asset_details/', views.asset_details, name="asset_details"),
    path('drop_data/', views.drop_data, name="drop_data"),
    path('get_branch/', views.get_branch, name="get_branch"),
    path('imageconvert/', views.imageconvert, name="imageconvert"),
    path('save_asset/', views.save_asset, name="save_asset"),
    path('branch_details/', views.branch_details, name="branch_details"),
    path('save_location/', views.save_location, name="save_location"),
    path('writeoff_summary/', views.writeoff_summary, name="writeoff_summary"),
    path('cat_change/', views.cat_change, name="cat_change"),
    path('cp_datechange/', views.cp_datechange, name="cp_datechange"),
    path('asset_checker/', views.asset_checker, name="asset_checker"),
    path('fa_category/', views.fa_category, name="fa_category"),
    path('fa_category_get/', views.fa_category_get, name="fa_category_get"),
    path('drop_branch/', views.drop_branch, name="drop_branch"),
    path('fa_assetadd/', views.fa_assetadd, name="fa_assetadd"),
    path('imageconvert/', views.imageconvert, name="imageconvert"),
    path('sale_make/', views.sale_make, name="sale_make"),
    path('dep_calculation/', views.dep_calculation, name="dep_calculation"),
    path('fin_year/', views.fin_year, name="fin_year"),

    path('drop_data/', views.drop_data, name="drop_data"),
    path('save_asset/', views.save_asset, name="save_asset"),
]
